CREATE SCHEMA xStore ;

-- Basic Details --
CREATE  TABLE BASIC_DETAIL (
  ID INT NOT NULL AUTO_INCREMENT,
  FIRST_NAME VARCHAR(45) NOT NULL,
  MIDDLE_NAME VARCHAR(45),
  LAST_NAME VARCHAR(45) NOT NULL,
  PHONE_NUMBER VARCHAR(45) NOT NULL,
  EMAIL VARCHAR(45) NOT NULL,
  ADDRESS VARCHAR(45) NOT NULL,
  CITY VARCHAR(45) NOT NULL,
  STATE VARCHAR(45) NOT NULL,
  COUNTRY VARCHAR(45) NOT NULL,
  PIN_CODE VARCHAR(45) NOT NULL,
  FAX VARCHAR(45),
  UPDATED_BY VARCHAR(45) NOT NULL,
  CREATED_BY VARCHAR(45) NOT NULL,
  UPDATED_DATE TIMESTAMP,
  CREATED_DATE TIMESTAMP,
  PRIMARY KEY (ID)
  );

 -- Client --
 CREATE TABLE CLIENT (
	ID INT NOT NULL AUTO_INCREMENT,
	BASIC_DETAIL_ID INT NOT NULL,
	USER_NAME VARCHAR(45) NOT NULL,
	PASSWORD VARCHAR(45) NOT NULL,
	UPDATED_BY VARCHAR(45) NOT NULL,
  	CREATED_BY VARCHAR(45) NOT NULL,
  	UPDATED_DATE TIMESTAMP,
  	CREATED_DATE TIMESTAMP,
  	STATUS BOOLEAN NOT NULL, -- Enable Shopping
  	PLAN_TYPE VARCHAR(10) NOT NULL,
	PRIMARY KEY (ID),
	UNIQUE KEY (USER_NAME),
	CONSTRAINT FK_CLIENT FOREIGN KEY (BASIC_DETAIL_ID) REFERENCES BASIC_DETAIL(ID)
	);
	
	
-- Group --
CREATE TABLE BRAND (
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(45) NOT NULL,
	CLIENT_ID INT NOT NULL,
	STATUS BOOLEAN NOT NULL,
	UPDATED_BY VARCHAR(45) NOT NULL,
  	CREATED_BY VARCHAR(45) NOT NULL,
  	UPDATED_DATE TIMESTAMP,
  	CREATED_DATE TIMESTAMP,
	PRIMARY KEY (ID),
	CONSTRAINT FK_BRAND FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(ID)
);
	
-- Store --
CREATE TABLE STORE (
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(45) NOT NULL,
	BRAND_ID INT NOT NULL,
	CURRENCY VARCHAR(45) NOT NULL,
	TIME_ZONE VARCHAR(45) NOT NULL,
	STATUS BOOLEAN NOT NULL,
	UPDATED_BY VARCHAR(45) NOT NULL,
  	CREATED_BY VARCHAR(45) NOT NULL,
  	UPDATED_DATE TIMESTAMP,
  	CREATED_DATE TIMESTAMP,
	PRIMARY KEY (ID),
	CONSTRAINT FK_STORE FOREIGN KEY (BRAND_ID) REFERENCES BRAND(ID)
);

 -- Store Users --
CREATE TABLE CUSTOMER (
	ID INT NOT NULL AUTO_INCREMENT,
	BASIC_DETAIL_ID INT NOT NULL,
	BRAND_ID INT NOT NULL,
	USER_NAME VARCHAR(45) NOT NULL,
	PASSWORD VARCHAR(45) NOT NULL,
	USER_TYPE VARCHAR(45) NOT NULL,
	NEWSLETTER BOOLEAN NOT NULL DEFAULT false,
	STATUS BOOLEAN NOT NULL,
	UPDATED_BY VARCHAR(45) NOT NULL,
  	CREATED_BY VARCHAR(45) NOT NULL,
  	UPDATED_DATE TIMESTAMP,
  	CREATED_DATE TIMESTAMP,
	PRIMARY KEY (ID),
	CONSTRAINT FK_CUSTOMER FOREIGN KEY (BASIC_DETAIL_ID) REFERENCES BASIC_DETAIL(ID),
	CONSTRAINT FK_BRAND_FOR_CUSTOMER FOREIGN KEY (BRAND_ID) REFERENCES BRAND(ID)
	);
	
 -- Products --
CREATE TABLE PRODUCT (
	ID INT NOT NULL AUTO_INCREMENT,
	PRODUCT_NAME VARCHAR(45) NOT NULL,
	DESCRIPTION VARCHAR(45),
	STORE_ID INT NOT NULL,
	UPDATED_BY VARCHAR(45) NOT NULL,
  	CREATED_BY VARCHAR(45) NOT NULL,
  	UPDATED_DATE TIMESTAMP,
  	CREATED_DATE TIMESTAMP,
	PRIMARY KEY (ID),
	CONSTRAINT FK_PRODUCT FOREIGN KEY (STORE_ID) REFERENCES STORE(ID)
	);
	
 -- Product Properties --
CREATE TABLE PRODUCT_PROPERTY (
	ID INT NOT NULL AUTO_INCREMENT,
	PRODUCT_ID INT NOT NULL,
	SIZE VARCHAR(45),
	PROPERTY VARCHAR(45),
	QUANTITY VARCHAR(45),
	UNIT VARCHAR(45),
	PRICE FLOAT(10,2),
	EFFECTIVE_PRICE FLOAT(10.2),
	UPDATED_BY VARCHAR(45) NOT NULL,
  	CREATED_BY VARCHAR(45) NOT NULL,
  	UPDATED_DATE TIMESTAMP,
  	CREATED_DATE TIMESTAMP,
	PRIMARY KEY (ID),
	CONSTRAINT FK_PRODUCT_PROPERTY FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID)
	);
	
-- Tag/Category --
	CREATE TABLE TAG (
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR (30) NOT NULL,
	STORE_ID INT NOT NULL,
	LEVEL INT NOT NULL,
	PARENT_ID INT NOT NULL,
	STATUS BOOLEAN NOT NULL,
	UPDATED_BY VARCHAR(45) NOT NULL,
  	CREATED_BY VARCHAR(45) NOT NULL,
  	UPDATED_DATE TIMESTAMP,
  	CREATED_DATE TIMESTAMP,
  	PRIMARY KEY (ID),
  	CONSTRAINT FK_TAG_STORE_ID FOREIGN KEY (STORE_ID) REFERENCES STORE (ID)
	);
	
-- Product Tag XREF --
	CREATE TABLE PRODUCT_TAG_XREF (
	ID INT NOT NULL AUTO_INCREMENT,
	TAG_ID INT NOT NULL,
	PRODUCT_ID INT NOT NULL,
	UPDATED_BY VARCHAR(45) NOT NULL,
  	CREATED_BY VARCHAR(45) NOT NULL,
  	UPDATED_DATE TIMESTAMP,
  	CREATED_DATE TIMESTAMP,
  	PRIMARY KEY (ID),
  	CONSTRAINT FK_TAG_ID_PRODUCT_TAG_XREF FOREIGN KEY (TAG_ID) REFERENCES TAG(ID),
	CONSTRAINT FK_PRODUCT_ID_PRODUCT_TAG_XREF FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID)
	);		
	
-- Wish List --	
CREATE TABLE WISH_LIST (
	ID INT NOT NULL AUTO_INCREMENT,
	STORE_ID INT NOT NULL,
	CUSTOMER_ID INT NOT NULL,
	NAME VARCHAR(45) NOT NULL,
	LIST_TYPE VARCHAR(45) NOT NULL,
	UPDATED_BY VARCHAR(45) NOT NULL,
  	CREATED_BY VARCHAR(45) NOT NULL,
  	UPDATED_DATE TIMESTAMP,
  	CREATED_DATE TIMESTAMP,
  	PRIMARY KEY (ID),
  	CONSTRAINT FK_STORE_FOR_WISH_LIST FOREIGN KEY (STORE_ID) REFERENCES STORE(ID),
	CONSTRAINT FK_CUSTOMER_FOR_WISH_LIST FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID)
	);
	
-- Wish List Xref--
CREATE TABLE WISH_LIST_XREF (
	ID INT NOT NULL AUTO_INCREMENT,
	WISH_LIST_ID INT NOT NULL,
	PRODUCT_PROP_ID INT NOT NULL,
	UPDATED_BY VARCHAR(45) NOT NULL,
  	CREATED_BY VARCHAR(45) NOT NULL,
  	UPDATED_DATE TIMESTAMP,
  	CREATED_DATE TIMESTAMP,
  	PRIMARY KEY (ID),
  	CONSTRAINT FK_PRODUCT_FOR_WISH_LIST_XREF FOREIGN KEY (PRODUCT_PROP_ID) REFERENCES PRODUCT_PROPERTY(ID),
  	CONSTRAINT FK_WISH_LIST_XREF FOREIGN KEY (WISH_LIST_ID) REFERENCES WISH_LIST(ID)
    );
	
-- Cart --
CREATE TABLE CART (
	ID INT NOT NULL AUTO_INCREMENT,
	STORE_ID INT NOT NULL,
	CUSTOMER_ID INT NOT NULL,
	STATUS BOOLEAN NOT NULL,
	UPDATED_BY VARCHAR(45) NOT NULL,
  	CREATED_BY VARCHAR(45) NOT NULL,
  	UPDATED_DATE TIMESTAMP,
  	CREATED_DATE TIMESTAMP,
	PRIMARY KEY (ID),
	CONSTRAINT FK_CART FOREIGN KEY (STORE_ID) REFERENCES STORE(ID),
	CONSTRAINT FK_CART_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID)
	);
	
-- Order --
CREATE TABLE STORE_ORDER (
	ID INT NOT NULL AUTO_INCREMENT,
	STORE_ID INT NOT NULL,
	CUSTOMER_ID INT NOT NULL,
	STATUS BOOLEAN NOT NULL,
	UPDATED_BY VARCHAR(45) NOT NULL,
  	CREATED_BY VARCHAR(45) NOT NULL,
  	UPDATED_DATE TIMESTAMP,
  	CREATED_DATE TIMESTAMP,
	PRIMARY KEY (ID),
	CONSTRAINT FK_ORDER FOREIGN KEY (STORE_ID) REFERENCES STORE(ID),
	CONSTRAINT FK_ORDER_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID)
	);
