-- DROP SCRIPTS --
DROP TABLE STORE_ORDER;
DROP TABLE CART;
DROP TABLE WISH_LIST_XREF;
DROP TABLE WISH_LIST;
DROP TABLE PRODUCT_TAG_XREF;
DROP TABLE TAG;
DROP TABLE PRODUCT_PROPERTY;
DROP TABLE PRODUCT;
DROP TABLE CUSTOMER;
DROP TABLE STORE;
DROP TABLE BRAND;
DROP TABLE CLIENT;
DROP TABLE BASIC_DETAIL;