INSERT INTO BASIC_DETAIL (FIRST_NAME, MIDDLE_NAME,LAST_NAME,PHONE_NUMBER,EMAIL,ADDRESS,CITY, STATE,COUNTRY,PIN_CODE,FAX,UPDATED_BY,CREATED_BY,UPDATED_DATE,CREATED_DATE) VALUES('Tarun','','Keswani','9740418418','tarunkeswani87@gmail.com','Park Street','Richmond','Virginia','United States','06067','','admin','admin',sysdate(),sysdate());

INSERT INTO CLIENT (BASIC_DETAIL_ID, USER_NAME,PASSWORD,PLAN_TYPE,STATUS,UPDATED_BY,CREATED_BY,UPDATED_DATE,CREATED_DATE) VALUES(1,'tarunkeswani87','qwerty','A',1,'admin','admin',sysdate(),sysdate());

INSERT INTO BRAND (NAME, CLIENT_ID, STATUS, UPDATED_BY,CREATED_BY,UPDATED_DATE,CREATED_DATE) VALUES ('Group6', 1, 1,'admin','admin',sysdate(),sysdate());

INSERT INTO STORE (NAME, BRAND_ID, CURRENCY, TIME_ZONE, STATUS, UPDATED_BY, CREATED_BY, UPDATED_DATE, CREATED_DATE) VALUES ('TarunGroup', 1, 'Paisa', 'IST', 1, 'admin', 'admin', sysdate(), sysdate());

INSERT INTO CUSTOMER (BASIC_DETAIL_ID, BRAND_ID, USER_NAME, PASSWORD, USER_TYPE, NEWSLETTER, STATUS, UPDATED_BY, CREATED_BY, UPDATED_DATE, CREATED_DATE) VALUES (1, 1, 'TarunCustomer', 'qwerty', 'Premium', 1, 1, 'admin', 'admin', sysdate(), sysdate());

INSERT INTO PRODUCT (PRODUCT_NAME, DESCRIPTION, STORE_ID, UPDATED_BY, CREATED_BY, UPDATED_DATE, CREATED_DATE) VALUES ('product1', 'productdescription', 1, 'admin', 'admin', sysdate(), sysdate());

INSERT INTO TAG (NAME, STORE_ID, LEVEL, PARENT_ID, STATUS, UPDATED_BY, CREATED_BY, UPDATED_DATE, CREATED_DATE) values ('tag1', 1, 1, 1, 1, 'admin', 'admin', sysdate(), sysdate());